apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barman-cloud-plugin
  namespace: argocd
  labels:
    source-type: helm
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: plugin-barman-cloud
      targetRevision: 0.7.0
      helm:
        releaseName: plugin-barman-cloud
        valueFiles:
          - $values/operators/barman-cloud/values.yaml
    - repoURL: https://github.com/bonzonkim/argocd-apps
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
