apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    # NOTE: version 7.1.2 is not working
    # https://github.com/argoproj/argo-cd/issues/18356
    targetRevision: 9.3.7
    chart: argo-cd
    helm:
      releaseName: argocd
      {{- $files := .Files }}
      values: |
        {{- $files.Get "conf/argo-cd.yaml" | nindent 12 }}
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
