apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: actions-runner-system
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: 0.23.7
    chart: actions-runner-controller
    helm:
      releaseName: actions-runner-controller
      valuesObject:
        authSecret:
          enabled: false
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: infisical-managed-secret
                key: GITHUB_PAT
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
