apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grammair-web
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: grammair-web=ghcr.io/bonzonkim/grammair-web/grammair-web
    argocd-image-updater.argoproj.io/grammair-web.update-strategy: semver
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/grammair-web.pull-secret: "pullsecret:argocd/grammair-packages"
    argocd-image-updater.argoproj.io/grammair-web.allow-tags: regexp:^1\.0\.[0-9]+$
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: grammair
  source:
    path: grammair/web
    repoURL: https://github.com/bonzonkim/argocd-apps.git
    targetRevision: main
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8}}
