apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: harbor
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: 1.17.2
    chart: harbor
    helm:
      releaseName: harbor
      {{- $files := .Files }}
      values: |
        {{- $files.Get "conf/harbor.yaml" | nindent 12 }}
  syncPolicy:
    {{- toYaml .Values.argocd.syncPolicy | nindent 8 }}
