apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: infisical-operator-system
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
    targetRevision: 0.6.2
    chart: secrets-operator
    helm:
      releaseName: infisical-secrets-operator
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
