apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-system
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.0-rc.0
    chart: istiod
    helm:
      releaseName: istiod
      {{- $files := .Files }}
      values: |
        {{- $files.Get "conf/istiod.yaml" | nindent 12 }}
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
