apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: prometheus
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.1.1
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      {{- $files := .Files }}
      values: |
        {{- $files.Get "conf/kube-prometheus-stack.yaml" | nindent 12 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true

