apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: minio
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.10.3
    chart: minio
    helm:
      releaseName: minio
      {{- $files := .Files }}
      values: |
        {{- $files.Get "conf/minio.yaml" | nindent 12 }}
  syncPolicy:
    {{- toYaml .Values.argocd.syncPolicy | nindent 8 }}
