apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phonelink-mysql
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: mysql
  source:
    path: mysql
    repoURL: https://github.com/bonzonkim/argocd-apps.git
    targetRevision: main
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
