apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pv-test
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: pv-test
  source:
    path: pv-test
    repoURL: https://github.com/bonzonkim/argocd-apps
    targetRevision: main
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
