apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-ci-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: flrhyme9/go-ci-test
    argocd-image-updater.argoproj.io/flrhyme9.go-ci-test.update-strategy: "1.0.0"
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
  source:
    path: test/kubernetes
    repoURL: https://github.com/bonzonkim/argocd-apps
    targetRevision: main
    kustomize:
      images:
        - flrhyme9/go-ci-test:1.0.0
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
