apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  source:
    repoURL: https://helm.vector.dev
    targetRevision: 0.46.0
    chart: vector
    helm:
      releaseName: vector
      {{- $files := .Files }}
      values: |
        {{- $files.Get "conf/vector.yaml" | nindent 12 }}
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
