apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: running-mate-postgresql
  namespace: argocd
  labels:
    source-type: helm
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 16.7.27
      helm:
        releaseName: running-mate-postgresql
        valueFiles:
          - $values/postgresql/postgresql/values.yaml
    - repoURL: https://github.com/bonzonkim/argocd-apps
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: running-mate
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
