apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: running-mate-postgresql-cnpg
  namespace: argocd
  labels:
    source-type: raw
spec:
  project: default
  source:
    repoURL: https://github.com/bonzonkim/argocd-apps
    targetRevision: main
    path: running-mate/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: running-mate
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
