nameOverrides: "std-prometheus-stack"

commonLabels:
  mgmt: bumgu

# -------------Global disabled-------------
global:
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false

# -------------Grafana-------------
grafana:
  enabled: false
# -------------Prometheus-------------
prometheus:
  namespace: prometheus
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - prom.k8s.bumgu.com
    paths:
      - /
    tls:
      - secretName: k8s-bumgu-com-tls
        hosts:
          - prom.k8s.bumgu.com

  prometheusSpec:
    externalUrl: https://prom.k8s.bumgu.com
    routePrefix: /
    # 서비스모니터 설정 -> 다른 네임스페이스에 있는 Service Monitor 사용을 위해 설정
    # By default, Prometheus only discovers PodMonitors within its own namespace.
    # This should be disabled by setting podMonitorSelectorNilUsesHelmValues to false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    enableFeatures:
      - remote-write-receiver
    enableRemoteWriteReceiver: true
    # 메트릭 스크랩
    scrapeInterval: "30s"
    scrapeTimeout: "15s"
    evaluationInterval: "16s"
    # 메트릭 보존 기간
    retention: 7d
    # 메트릭 최대 사이즈
    retentionSize: "10GiB"
    replicas: 1
    # 리소스 설정
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    additionalScrapeConfigs:
      scrape_configs:
        - job_name: minio-job
          bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoic3RkIiwiZXhwIjo0ODkxMjk4NzI0fQ.bowbEx5HiW6WGspxRjGXl38GVj1W5CmGFgedGCbA9W4DdzTwdRGHpXPZWFYrOIDDjjj0sN4roknzynmRF0_REQ
          metrics_path: /minio/v2/metrics/cluster
          scheme: https
          static_configs:
          - targets: [minio-test-api.k8s.bumgu.com]
        - job_name: minio-job-bucket
          bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoic3RkIiwiZXhwIjo0ODkxMjk4NzM3fQ.rAn1aXKCxwyQXQOjDYwZa39lZyHJYN4XsmpO8xjV-mKE5bkz_EfhC8l0eP5iYQax1MDTTds3vsUR_sKoMUFKeg
          metrics_path: /minio/v2/metrics/bucket
          scheme: https
          static_configs:
          - targets: [minio-test-api.k8s.bumgu.com]
        - job_name: minio-job-node
          bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoic3RkIiwiZXhwIjo0ODkxMjk4NzQyfQ.VQiqCiKPtRJi9iqbNL7IpH_EL1D55WbsF9Bk7wZogTVbqBvn9EDE88Ve8hZI-jv5ZG5mJ8QRskx6eOtbGXzKGg
          metrics_path: /minio/v2/metrics/node
          scheme: https
          static_configs:
          - targets: [minio-test-api.k8s.bumgu.com]
        - job_name: minio-job-resource
          bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoic3RkIiwiZXhwIjo0ODkxMjk4NzQ5fQ.t0Ove18VkkWmy5Zv_La0VEv4DjuLgppdjK-ioT-vxfEeCjqV_j36lNGl7W0CIt1NhtniS40Kn1Gr0QCTWvOQZg
          metrics_path: /minio/v2/metrics/resource
          scheme: https
          static_configs:
          - targets: [minio-test-api.k8s.bumgu.com]








crds:
  enabled: true

# -------------Alertmanager-------------
alertmanager:
  namespace: prometheus
  enabled: false
