grafana:
  enabled: false
alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack
    podMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack
    serviceMonitorNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        release: kube-prometheus-stack
    ruleNamespaceSelector: {}
