apiVersion: v1
kind: Service
metadata:
  name: grammair-server-service
  namespace: grammair
spec:
  selector:
    app: grammair-server  
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
