apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ph-backend-pvc
  namespace: phonelink
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
