apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-raw
  namespace: argocd
spec:
  goTemplate: true
  preserveResourcesOnDeletion: true

  generators:
    - git:
        repoURL: 'https://github.com/bonzonkim/argocd-apps'
        revision: main
        files:
          - path: '*/*/config.json'
        values:
          path: '{{ trimSuffix "/config.json" .path.path }}'

  selector:
    matchLabels:
      sourceType: raw

  template:
    metadata:
      name: '{{ .appName }}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/bonzonkim/argocd-apps'
        targetRevision: main
        path: '{{ .path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ default (index (splitList "/" .path) 0) .namespace }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
