apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-helm
  namespace: argocd
spec:
  goTemplate: true
  preserveResourcesOnDeletion: true

  generators:
    - git:
        repoURL: 'https://github.com/bonzonkim/argocd-apps'
        revision: main
        files:
          - path: '*/*/config.json'
        values:
          path: '{{ trimSuffix "/config.json" .path.path }}'
      selector:
        matchLabels:
          sourceType: helm

  template:
    metadata:
      name: '{{ .appName }}'
    spec:
      project: default

      sources:
        - repoURL: '{{ .repoURL }}'
          chart: '{{ .chart }}'
          targetRevision: '{{ .targetRevision }}'
          helm:
            releaseName: '{{ default .chart .releaseName }}'
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/{{ .values.path }}/values.yaml'
        - repoURL: 'https://github.com/bonzonkim/argocd-apps'
          targetRevision: main
          ref: values
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

  # config.json에 ignoreDifferences 설정이 있을 경우에만 렌더링됩니다.
  templatePatch: |
    {{- if .ignoreDifferences }}
    spec:
      ignoreDifferences:
      {{- range .ignoreDifferences }}
        - group: '{{ default "" .group }}'
          kind: '{{ .kind }}'
          {{- if .name }}
          name: '{{ .name }}'
          {{- end }}
          {{- if .jsonPointers }}
          jsonPointers:
          {{- range .jsonPointers }}
            - '{{ . }}'
          {{- end }}
          {{- end }}
      {{- end }}
    {{- end }}
