apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-raw
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: https://github.com/bonzonkim/argocd-apps
        revision: main
        files:
          - path: "*/*/application.yaml"
      selector:
        matchLabels:
          metadata.labels.source-type: raw
  template:
    metadata:
      name: "{{ .metadata.name }}"
    spec:
      project: "{{ .spec.project }}"
      destination:
        server: "{{ .spec.destination.server }}"
        namespace: "{{ .spec.destination.namespace }}"
  templatePatch: |
    {{- $metadata := deepCopy .metadata }}
    {{- $spec := deepCopy .spec }}
    {{- $_ := unset $spec "project" }}
    {{- dict "metadata" $metadata "spec" $spec | mustToPrettyJson }}
