apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-kube-prometheus-stack
  namespace: argocd
  labels:
    source-type: helm
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 79.0.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/prometheus/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/bonzonkim/argocd-apps
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
