grafana:
  enabled: false
alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack
    podMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack
    serviceMonitorNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        release: kube-prometheus-stack
    ruleNamespaceSelector: {}
    additionalScrapeConfigs:
      - job_name: b9
        static_configs:
          - targets: ["100.95.215.51:9100"]
            labels:
              alias: mac
