apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k3s-cluster
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: minio
    release: minio
  name: export-0-minio-0
  namespace: minio
  uid: 0424345d-e1a3-4619-b5e4-aac534abdbc3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "rancher.io/local-path"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k3s-cluster
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: minio
    release: minio
  name: export-1-minio-0
  namespace: minio
  uid: 67e8cafc-ee4c-4c2d-a3e3-dfc891942fe0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "rancher.io/local-path"
