apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    #    pv.kubernetes.io/bind-completed: 'yes'
    #    pv.kubernetes.io/bound-by-controller: 'yes'
    #    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    #    volume.kubernetes.io/selected-node: k3s-cluster
    #    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: minio
    release: minio
  name: export-0-minio-0
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-path"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    #    pv.kubernetes.io/bind-completed: 'yes'
    #    pv.kubernetes.io/bound-by-controller: 'yes'
    #    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    #    volume.kubernetes.io/selected-node: k3s-cluster
    #    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: minio
    release: minio
  name: export-1-minio-0
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-path"
