name: Go CI Test

on:
  push:
    branches:
      - "main"
    paths:
      - "test/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "test/**"
    
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: test
          file: test/Dockerfile
          push: true
          tags: flrhyme9/go-ci-test:latest
