name: ip.bumgu.com build

on:
  push:
    branches:
      - "main"
    paths:
      - "ip.bumgu.com"
  pull_request:
    branches:
      - "main"
    paths:
      - "ip.bumgu.com"

jobs:
  ip-bumgu-com:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ip.bumgu.com

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ip.bumgu.com
          file: ip.bumgu.com/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: flrhyme9/ip-bumgu-com:1.0.0
